name: Publish pipeline
pr: none
trigger:
  tags:
    include:
    - '*'

stages:

- stage: pack
  displayName: Pack
  jobs: 
  - job: pack
    displayName: Pack
    pool:
      vmImage: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - script: |
        dotnet pack Library \
        --configuration Release \
        --output output \
        -property:"Version=$(Build.SourceBranchName)" \
        -property:"AllowedReferenceRelatedFileExtensions="
    - publish: output
      artifact: nupkg

- stage: publish
  displayName: Publish
  variables:
  - group: Nuget
  jobs:
  - deployment: publish
    displayName: Publish
    pool:
      vmImage: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    environment: Nuget
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: nupkg
          - script: |
              dotnet nuget push $(Pipeline.Workspace)/nupkg/*.nupkg \
              --source https://api.nuget.org/v3/index.json \
              --skip-duplicate \
              --api-key $(ApiKey)