name: Build pipeline
trigger:
  branches:
    include:
    - main

stages:

- stage: build
  displayName: Build
  jobs: 
  - template: .azure-pipeline-templates/.dotnet-build.yml
    parameters:
      project: 'Library'
  - template: .azure-pipeline-templates/.dotnet-build.yml
    parameters:
      sdk: '5.0'
      framework: 'net5.0'
      project: 'Library'
  - template: .azure-pipeline-templates/.dotnet-build.yml
    parameters:
      sdk: '3.1'
      framework: 'netcoreapp3.1'
      project: 'Library'

- stage: test
  displayName: Test
  jobs: 
  - template: .azure-pipeline-templates/.dotnet-test.yml
    parameters:
      project: 'Tests.UnitTests'
  - template: .azure-pipeline-templates/.dotnet-test.yml
    parameters:
      sdk: '5.0'
      framework: 'net5.0'
      project: 'Tests.UnitTests'
  - template: .azure-pipeline-templates/.dotnet-test.yml
    parameters:
      sdk: '3.1'
      framework: 'netcoreapp3.1'
      project: 'Tests.UnitTests'
