parameters:
- name: sdk
  type: string
  default: '6.0'
- name: framework
  type: string
  default: 'net6.0'
- name: configuration
  type: string
  default: 'Release'
- name: project
  type: string
  default: '.'
  
jobs:
- job: dotnet_build_${{ replace(parameters['framework'], '.', '_') }}
  pool:
    vmImage: ubuntu-latest
  displayName: Build ${{ parameters.framework }}
  steps:
  - template: .dotnet-restore.yml
  - task: UseDotNet@2
    inputs:
      version: ${{ parameters.sdk }}.x
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '${{ parameters.project }}'
      packagesDirectory: packages
      arguments: '--configuration ${{ parameters.configuration }} --framework ${{ parameters.framework }} --no-restore'
