name: Release
run-name: Release
on:
  push:
    tags:
      - '*'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Pack
        run: |
          dotnet pack Library \
          --configuration Release \
          --output output \
          -property:"Version=${{ vars.GITHUB_REF_NAME }}" \
          -property:"AllowedReferenceRelatedFileExtensions="
      - name: actions/create-release@v1
        with:
            tag_name: ${{ vars.GITHUB_REF_NAME }}
            release_name: Release ${{ vars.GITHUB_REF_NAME }}
            body_path: ./.github/releases/${{ vars.GITHUB_REF_NAME }}.md
      - name: NuGet push
        run: |
          dotnet nuget push ./output/*.nupkg \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate \
          --api-key ${{ secrets.NUGET_API_KEY }}